Add support for go.delivery.report.fields
confluentinc/confluent-kafka-go pull request #530
Opened 2020-09-17 15:08 UTC by kevinconaway

@edenhill 
This configuration property will allow users to enable/disable certain fields of the delivery reports to reduce allocations.

Only the key & value are currently supported

Addresses #524

2020-11-17 19:32 UTC, kevinconaway commented
@edenhill any update here ?

2020-11-18 09:24 UTC, edenhill requested changes
Left some comments.
Please add a test case producer_test.go where you produce a message with a short message.timeout.ms (1ms) and verify that only the enabled messageFields are available.

2020-11-18 09:24 UTC, edenhill commented on kafka/handle.go
> +	mf *messageFields
Can we have a more descriptive field name than mf? msgFields?

2020-11-18 09:24 UTC, edenhill commented on kafka/producer.go
> +//											   Allowed values: all, none, key, value
Use space for indent

2020-11-18 09:24 UTC, edenhill commented on kafka/producer.go
> +	switch v {
I think it would be better to move the following logic into newMessageFields

2020-11-18 09:24 UTC, edenhill commented on kafka/producer.go
> +			}
Should error out on unknown fields.

2020-11-18 09:24 UTC, edenhill commented on kafka/handle.go
> +// messageFields controls which fields are deserialized for producer delivery reports & incoming messages
They're not really deserialized, maybe "which fields are made available"?

2020-11-18 09:24 UTC, edenhill commented on kafka/handle.go
> +	key   bool
` // Message.Key` and `// Message.Value`

2021-02-04 14:18 UTC, kevinconaway commented
@edenhill Sorry about the delay here.  

I believe that I have addressed your comments, please let me know what, if anything, else needs doing.  Thank you!

2021-02-16 12:12 UTC, kevinconaway commented
@edenhill thoughts here?

2021-02-17 08:29 UTC, edenhill commented
Looks good!
Can you rebase the PR on latest master to fix the conflicts?

2021-02-17 12:37 UTC, kevinconaway commented
Done although I didn't see any merge conflicts here.  Is there something I'm not seeing?

2021-02-17 13:30 UTC, edenhill commented
Huhm, github says this:
> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

Try to rebase and squash your PR on top of master instead of merging master, like so:
```bash
$ git fetch upstream   # or whatever our repo remote is named)
$ git rebase -i origin/upstream 
# In the editor, fixup (f)  all commits into one single commit. Save and quit.
$ git push --force ......
```

2021-02-17 13:49 UTC, kevinconaway commented
Done.  The PR dialog still doesn't show any conflicts for me, how strange

<img width="1006" alt="Screen Shot 2021-02-17 at 8 47 45 AM" src="https://user-images.githubusercontent.com/6921953/108213389-f803cc00-70fc-11eb-8f28-ba9af544b2aa.png">

2021-02-17 13:50 UTC, edenhill commented
Looks good now, thanks!

2021-02-17 13:58 UTC, edenhill commented
[clabot:check]

2021-02-17 13:58 UTC, merged

2021-02-17 13:58 UTC, edenhill commented
Thank you, Kevin!