Add service.yml for adding new project to semaphore CI
confluentinc/confluent-kafka-go pull request #789
Opened 2022-06-03 21:06 UTC by jliunyu

For semaphore CI migration, we need to first add new project to semaphore according to https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/1342058645/Semaphore+FAQ#How-can-I-add-my-new-project-to-semaphore2. We need to add service.yml to the master branch and then run a jenkins job to add our project to the semaphore CI.

2022-06-03 21:29 UTC, xli1996 commented on service.yml
> +
nit: extra line.

2022-06-03 21:30 UTC, xli1996 approved these changes

2022-06-08 08:33 UTC, edenhill requested changes

2022-06-08 08:33 UTC, edenhill commented on service.yml
> +# Add the following 2 lines if you want the automatically generated .semaphore files
remove

2022-06-08 08:33 UTC, edenhill commented on service.yml
> +  repo_name: confluentinc/confluent-kafka-go # for example, confluentinc/cc-new-service
remove comment

2022-06-13 18:39 UTC, edenhill approved these changes
LGTM

2022-06-14 22:07 UTC, merged