fix: initialise schema-registry tlsConf.RootCAs value (invalid memory address or nil pointer)
confluentinc/confluent-kafka-go pull request #856
Opened 2022-09-07 14:06 UTC by ju-popov

panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100fcd0e0]

goroutine 1 [running]:
crypto/x509.(*CertPool).addCertFunc(...)
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/crypto/x509/cert_pool.go:189
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, {0x1400047a000?, 0x1400031f998?, 0x100dabf7c?})
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/crypto/x509/cert_pool.go:227 +0x260
github.com/confluentinc/confluent-kafka-go/schemaregistry.configureTLS(0x1400046da01?, 0x140001cd500)
	/Users/ju/github.com/sumup/confluent-kafka-go/schemaregistry/rest_service.go:176 +0x1f0
github.com/confluentinc/confluent-kafka-go/schemaregistry.configureTransport(0x1400031fbf8)
	/Users/ju/github.com/sumup/confluent-kafka-go/schemaregistry/rest_service.go:190 +0x38
github.com/confluentinc/confluent-kafka-go/schemaregistry.newRestService(0x1400031fbf8)
	/Users/ju/github.com/sumup/confluent-kafka-go/schemaregistry/rest_service.go:126 +0x128
github.com/confluentinc/confluent-kafka-go/schemaregistry.NewClient(0x1400031fbf8)
	/Users/ju/github.com/sumup/confluent-kafka-go/schemaregistry/schemaregistry_client.go:229 +0x15c

2022-09-07 14:08 UTC, syndbg approved these changes
LGTM. We've hit this issue when needing to provide a TLS CA cert.

2022-09-21 05:10 UTC, milindl requested changes
Thank you for finding this and for the fix.
It looks mostly good to me.
I've requested a minor change, and I'd like either @emasab or @rayokota to weigh in.

2022-09-21 05:10 UTC, milindl commented on schemaregistry/rest_service.go
>  		tlsConf.RootCAs.AppendCertsFromPEM(caCert)
I think at this point we should also check the return value for this and return an error if we were not able to parse the certificate

```
		if !tlsConf.RootCAs.AppendCertsFromPEM(caCert) {
			return fmt.Errorf("could not parse certificate from %s", caFile)
		}
```

2022-09-22 00:49 UTC, rayokota reviewed
Thanks, looks good assuming @milindl 's additional suggestion is also added.

2022-09-22 16:02 UTC, bibyzan commented
Bump on this one please, it seems SSL enabled schema registration is broken without these changes.

2023-01-06 10:15 UTC, milindl commented
Closing with #878 , which also adds the error handling, and a unit test

2023-01-06 10:15 UTC, closed without merging